In [430]:
import pandas as pd
import numpy as np
import sqlite3

In [431]:
inventory_levels = pd.read_csv('INVENTORY_LEVELS-data.csv')
product_forecast = pd.read_csv('PRODUCT_FORECAST-data.csv')
sales_target = pd.read_csv('SALES_TARGET-data.csv', encoding='cp1252')

crm = sqlite3.connect('CRM-data.sqlite')
go_sales = sqlite3.connect('GO_SALES-data.sqlite')
go_staff = sqlite3.connect('GO_STAFF-data.sqlite')

In [432]:
age_group = pd.read_sql("SELECT * FROM age_group;",crm)
customer_contact = pd.read_sql("SELECT * FROM customer_contact;",crm)
customer_segment = pd.read_sql("SELECT * FROM customer_segment;",crm)
customer_type = pd.read_sql("SELECT * FROM customer_type;",crm)
sales_territory = pd.read_sql("SELECT * FROM sales_territory;",crm)
customer_store = pd.read_sql("SELECT * FROM customer_store;",crm)
crm_country = pd.read_sql("SELECT * FROM crm_country;",crm)
customer = pd.read_sql("SELECT * FROM customer;",crm)
sales_demographic = pd.read_sql("SELECT * FROM sales_demographic;",crm)
customer_headquarters = pd.read_sql("SELECT * FROM customer_headquarters;",crm)

In [433]:
order_method = pd.read_sql("SELECT * FROM order_method;",go_sales)
product_line = pd.read_sql("SELECT * FROM product_line;",go_sales)
retailer_site = pd.read_sql("SELECT * FROM retailer_site;",go_sales)
return_reason = pd.read_sql("SELECT * FROM return_reason;",go_sales)
returned_item = pd.read_sql("SELECT * FROM returned_item;",go_sales)
order_details = pd.read_sql("SELECT * FROM order_details;",go_sales)
order_header = pd.read_sql("SELECT * FROM order_header;",go_sales)
product_type = pd.read_sql("SELECT * FROM product_type;",go_sales)
product = pd.read_sql("SELECT * FROM product;",go_sales)
sales_staff = pd.read_sql("SELECT * FROM sales_staff;",go_sales)
country = pd.read_sql("SELECT * FROM country;",go_sales)
sales_branch = pd.read_sql("SELECT * FROM sales_branch;",go_sales)

In [434]:
satisfaction = pd.read_sql("SELECT * FROM satisfaction;",go_staff)
training = pd.read_sql("SELECT * FROM training;",go_staff)
course = pd.read_sql("SELECT * FROM course;",go_staff)
sales_office = pd.read_sql("SELECT * FROM sales_office;",go_staff)
satisfaction_type = pd.read_sql("SELECT * FROM satisfaction_type;",go_staff)
sales_representative = pd.read_sql("SELECT * FROM sales_representative;",go_staff)

In [435]:
# ik maak er een lijst van om in 1 overzicht te kunnen zien in welke databases een lege colom zit

lijstje = [
    ("inventory_levels", inventory_levels),
    ("product_forecast", product_forecast),
    ("sales_target", sales_target),
    ("age_group", age_group),
    ("customer_contact", customer_contact),
    ("customer_segment", customer_segment),
    ("customer_type", customer_type),
    ("sales_territory", sales_territory),
    ("customer_store", customer_store),
    ("crm_country", crm_country),
    ("customer", customer),
    ("sales_demographic", sales_demographic),
    ("customer_headquarters", customer_headquarters),
    ("order_method", order_method),
    ("product_line", product_line),
    ("retailer_site", retailer_site),
    ("return_reason", return_reason),
    ("order_details", order_details),
    ("order_header", order_header),
    ("product_type", product_type),
    ("product", product),
    ("sales_staff", sales_staff),
    ("country", country),
    ("sales_branch", sales_branch),
    ("satisfaction", satisfaction),
    ("training", training),
    ("course", course),
    ("sales_office", sales_office),
    ("satisfaction_type", satisfaction_type),
    ("sales_representative", sales_representative)
]


for naam, df in lijstje:
    for col in df.columns:
        if df[col].isna().any():
            print(f"{naam} - {col}")

customer_contact - EXTENSION
customer_contact - FAX
customer_contact - E_MAIL
customer_store - ADDITION
customer_store - STATE
customer_store - ZIPCODE
customer - CUSTOMER_CODEMR
customer_headquarters - ADDRESS2
customer_headquarters - REGION
customer_headquarters - POSTAL_ZONE
customer_headquarters - PHONE
customer_headquarters - FAX
retailer_site - ADDRESS2
retailer_site - REGION
retailer_site - POSTAL_ZONE
sales_staff - EXTENSION
sales_branch - ADDRESS2
sales_branch - REGION
sales_office - ADDITION
sales_office - REGION
sales_representative - EXTENSION

In [436]:
sales_representative['EXTENSION'].info()
sales_representative['EXTENSION'] = sales_representative['EXTENSION'].fillna(0)
sales_representative['EXTENSION'].info()

<class 'pandas.Series'>
RangeIndex: 102 entries, 0 to 101
Series name: EXTENSION
Non-Null Count  Dtype
--------------  -----
100 non-null    str
dtypes: str(1)
memory usage: 948.0 bytes
<class 'pandas.Series'>
RangeIndex: 102 entries, 0 to 101
Series name: EXTENSION
Non-Null Count  Dtype
--------------  -----
102 non-null    object
dtypes: object(1)
memory usage: 948.0+ bytes

In [437]:
sales_office[['ADDITION', 'REGION']].info()
sales_office['ADDITION'] = sales_office['ADDITION'].fillna('-')
sales_office['REGION'] = sales_office['REGION'].fillna(sales_office['REGION'].mode()[0])
sales_office[['ADDITION', 'REGION']].info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADDITION  9 non-null      str
 1   REGION    15 non-null     str
dtypes: str(2)
memory usage: 580.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADDITION  28 non-null     str
 1   REGION    28 non-null     str
dtypes: str(2)
memory usage: 580.0 bytes

In [438]:
sales_branch[['ADDRESS2', 'REGION']].info()
sales_branch['ADDRESS2'] = sales_branch['ADDRESS2'].fillna(sales_branch['ADDRESS1'].mode()[0])
sales_branch['REGION'] = sales_branch['REGION'].fillna(sales_branch['REGION'].mode()[0])
sales_branch[['ADDRESS2', 'REGION']].info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADDRESS2  8 non-null      str
 1   REGION    14 non-null     str
dtypes: str(2)
memory usage: 532.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADDRESS2  25 non-null     str
 1   REGION    25 non-null     str
dtypes: str(2)
memory usage: 532.0 bytes

In [439]:
sales_staff['EXTENSION'].info()
sales_staff['EXTENSION'] = sales_staff['EXTENSION'].fillna(sales_staff['EXTENSION'].mode()[0])
sales_staff['EXTENSION'].info()

<class 'pandas.Series'>
RangeIndex: 96 entries, 0 to 95
Series name: EXTENSION
Non-Null Count  Dtype
--------------  -----
94 non-null     str
dtypes: str(1)
memory usage: 900.0 bytes
<class 'pandas.Series'>
RangeIndex: 96 entries, 0 to 95
Series name: EXTENSION
Non-Null Count  Dtype
--------------  -----
96 non-null     str
dtypes: str(1)
memory usage: 900.0 bytes

In [440]:
retailer_site[['ADDRESS2', 'REGION', 'POSTAL_ZONE']].info()

smollist = 'REGION', 'POSTAL_ZONE'
retailer_site['ADDRESS2'] = retailer_site['ADDRESS2'].fillna(retailer_site['ADDRESS1'])
for i in smollist:
    retailer_site[i] = retailer_site[i].fillna(retailer_site[i].mode()[0])

retailer_site[['ADDRESS2', 'REGION', 'POSTAL_ZONE']].info()

<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ADDRESS2     105 non-null    str
 1   REGION       251 non-null    str
 2   POSTAL_ZONE  390 non-null    str
dtypes: str(3)
memory usage: 9.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ADDRESS2     391 non-null    str
 1   REGION       391 non-null    str
 2   POSTAL_ZONE  391 non-null    str
dtypes: str(3)
memory usage: 9.3 KB

In [441]:
customer_headquarters[['ADDRESS2', 'REGION', 'POSTAL_ZONE', 'PHONE', 'FAX']].info()


smollist = 'REGION', 'POSTAL_ZONE', 'PHONE', 'FAX'
customer_headquarters['ADDRESS2'] = customer_headquarters['ADDRESS2'].fillna(customer_headquarters['ADDRESS1'])
for i in smollist:
    customer_headquarters[i] = customer_headquarters[i].fillna(customer_headquarters[i].mode()[0])

customer_headquarters[['ADDRESS2', 'REGION', 'POSTAL_ZONE', 'PHONE', 'FAX']].info()

customer_headquarters['CUSTOMER_CODEMR'] = customer_headquarters['CUSTOMER_CODEMR'].astype(int)
customer_headquarters['COUNTRY_CODE'] = customer_headquarters['COUNTRY_CODE'].astype(int)
customer_headquarters = customer_headquarters.rename(columns={
    'CUSTOMER_CODEMR': 'CUSTOMER_CODE_HQ',
    'COUNTRY_CODE': 'COUNTRY'
})
customer_headquarters = customer_headquarters.rename(columns={
    'ADDRESS1': 'ADRESS1',
    'ADDRESS2': 'ADRESS2'
})

<class 'pandas.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ADDRESS2     110 non-null    str
 1   REGION       221 non-null    str
 2   POSTAL_ZONE  412 non-null    str
 3   PHONE        413 non-null    str
 4   FAX          411 non-null    str
dtypes: str(5)
memory usage: 16.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ADDRESS2     414 non-null    str
 1   REGION       414 non-null    str
 2   POSTAL_ZONE  414 non-null    str
 3   PHONE        414 non-null    str
 4   FAX          414 non-null    str
dtypes: str(5)
memory usage: 16.3 KB

In [442]:
customer['CUSTOMER_CODEMR'].info()
customer['CUSTOMER_CODEMR'] = customer['CUSTOMER_CODEMR'].fillna(customer['CUSTOMER_CODEMR'].mode()[0])
customer['CUSTOMER_CODEMR'].info()

<class 'pandas.Series'>
RangeIndex: 109 entries, 0 to 108
Series name: CUSTOMER_CODEMR
Non-Null Count  Dtype
--------------  -----
87 non-null     str
dtypes: str(1)
memory usage: 1004.0 bytes
<class 'pandas.Series'>
RangeIndex: 109 entries, 0 to 108
Series name: CUSTOMER_CODEMR
Non-Null Count  Dtype
--------------  -----
109 non-null    str
dtypes: str(1)
memory usage: 1004.0 bytes

In [443]:
customer_store[['ADDITION', 'STATE', 'ZIPCODE']].info()

smollist = 'STATE', 'ZIPCODE'

customer_store['ADDITION'] = customer_store['ADDITION'].fillna('-')
customer_store['STATE']
for i in smollist:
    customer_store[i] = customer_store[i].fillna(customer_store[i].mode()[0])

customer_store[['ADDITION', 'STATE', 'ZIPCODE']].info()

customer_store['CUSTOMER_SITE_CODE'] = customer_store['CUSTOMER_SITE_CODE'].astype(int)
customer_store['ACTIVE_INDICATOR'] = customer_store['ACTIVE_INDICATOR'].astype(bool)

<class 'pandas.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADDITION  104 non-null    str
 1   STATE     251 non-null    str
 2   ZIPCODE   360 non-null    str
dtypes: str(3)
memory usage: 8.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ADDITION  361 non-null    str
 1   STATE     361 non-null    str
 2   ZIPCODE   361 non-null    str
dtypes: str(3)
memory usage: 8.6 KB

In [444]:
customer_contact[['EXTENSION', 'FAX', 'E_MAIL']].info()

smollist = 'FAX', 'E_MAIL'
customer_contact['EXTENSION'] = customer_contact['EXTENSION'].fillna('0')
for i in smollist:
    customer_contact[i] = customer_contact[i].fillna(customer_contact[i].mode()[0])

customer_contact[['EXTENSION', 'FAX', 'E_MAIL']].info()

customer_contact["CUSTOMER_CONTACT_CODE"] = customer_contact["CUSTOMER_CONTACT_CODE"].astype(int)
customer_contact["EXTENSION"] = customer_contact["EXTENSION"].astype(int)

<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   EXTENSION  70 non-null     str
 1   FAX        390 non-null    str
 2   E_MAIL     386 non-null    str
dtypes: str(3)
memory usage: 9.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   EXTENSION  391 non-null    str
 1   FAX        391 non-null    str
 2   E_MAIL     391 non-null    str
dtypes: str(3)
memory usage: 9.3 KB

In [445]:
customer

,CUSTOMER_CODE,CUSTOMER_CODEMR,COMPANY_NAME,CUSTOMER_TYPE_CODE
0,1,1,ActiForme,5
1,15,234,SportsClub,1
2,23,229,Anapurna,3
3,32,230,Cordages Discount,4
4,33,228,Altitudes extrêmes,6
...,...,...,...,...
104,193,428,Allo Allo,3
105,194,429,Caravanserai,6
106,209,415,Ausrüstungshaus Globetrotter,2
107,210,1,Golfer-Paradies,1
108,211,414,Outdoor-Fachgeschäft Müller,6

In [446]:
product_forecast['num'] = product_forecast.index
sales_target['num'] = sales_target.index
inventory_levels['INVENTORY_LEVELS_CODE'] = inventory_levels.index
satisfaction['SATISFACTION_CODE'] = satisfaction.index

In [447]:
crm_country = crm_country.rename(columns={"SALES_TERRITORY_CODE": "SALES_TERRITORY"})
return_reason = return_reason.rename(columns={'RETURN_DESCRIPTION_EN': 'RETURN_DESCRIPTION'})
sales_office = sales_office.rename(columns={'COUNTRY_CODE': 'COUNTRY'})
product_type = product_type.rename(columns={'PRODUCT_LINE_CODE': 'PRODUCT_LINE'})
sales_branch = sales_branch.rename(columns={'ADDRESS1': 'ADRESS1',
                                            'ADDRESS2': 'ADRESS2',
                                            'COUNTRY_CODE': 'COUNTRY',
                                            'POSTAL_ZONE': 'POSTAL_CODE'})
product = product.rename(columns={'PRODUCT_TYPE_CODE': 'PRODUCT_TYPE',
                                  'PRODUCT_IMAGE': 'PRODUCT_IMG'})
sales_staff = sales_staff.rename(columns={'SALES_BRANCH_CODE': 'SALES_BRANCH'})
sales_representative = sales_representative.rename(columns={'SALES_OFFICE_CODE': 'SALES_OFFICE',
                                                            'MANAGER_CODE': 'MANAGER'})
customer = customer.rename(columns={'CUSTOMER_TYPE_CODE': 'CUSTOMER_TYPE',
                                    'CUSTOMER_CODEMR': 'CUSTOMER_HEADQUARTERS'})
customer_store = customer_store.rename(columns={'CUSTOMER_CODE':'CUSTOMER', 'COUNTRY_CODE':'CRM_COUNTRY', 'CUSTOMER_SITE_CODE':'CUSTOMER_STORE_CODE'})
customer_contact = customer_contact.rename(columns={'CUSTOMER_SITE_CODE':'CUSTOMER_STORE'})
sales_demographic = sales_demographic.rename(columns={'CUSTOMER_CODEMR':'CUSTOMER_HEADQUARTERS', 'AGE_GROUP_CODE':'AGE_GROUP'})
order_header = order_header.rename(columns={'SALES_BRANCH_CODE':'SALES_BRANCH', 'SALES_STAFF_CODE':'SALES_STAFF', 'RETAILER_SITE_CODE':'RETAILER_SITE', 'ORDER_METHOD_CODE':'ORDER_METHOD'})
order_details = order_details.rename(columns={'ORDER_NUMBER':'ORDER_HEADER', 'PRODUCT_NUMBER':'PRODUCT'})
returned_item = returned_item.rename(columns={'ORDER_DETAIL_CODE':'ORDER_DETAILS', 'RETURN_REASON_CODE':'RETURN_REASON'})
inventory_levels = inventory_levels.rename(columns={'PROTUCT_NUMBER':'PRODUCT'})
product_forecast = product_forecast.rename(columns={'num':'PRODUCT_FORECAST_CODE', 'PRODUCT_NUMBER':'PRODUCT'})
inventory_levels = inventory_levels.rename(columns={'INVENTORY_LEVELS_CODE':'INVENTORY_LEVELS_CODE', 'PRODUCT_NUMBER':'PRODUCT'})
sales_target = sales_target.rename(columns={'PRODUCT_NUMBER':'PRODUCT', 'num':'SALES_TARGET_CODE', 'SALES_STAFF_CODE': 'SALES_STAFF'})

In [448]:
satisfaction

     YEAR SALES_REPRESENTATIVE_CODE SATISFACTION_TYPE_CODE  SATISFACTION_CODE
0    2004                         4                      5                  0
1    2004                         5                      4                  1
2    2004                         6                      3                  2
3    2004                         7                      4                  3
4    2004                        12                      4                  4
..    ...                       ...                    ...                ...
296  2006                       120                      4                296
297  2006                       121                      4                297
298  2006                       122                      4                298
299  2006                       123                      3                299
300  2006                       124                      5                300

[301 rows x 4 columns]

In [449]:
valid = set(country["COUNTRY_CODE"])

sales_office = sales_office[
    sales_office["COUNTRY"].isin(valid)
]

valid_codes = country['COUNTRY_CODE'].unique()
customer_headquarters = customer_headquarters[customer_headquarters['COUNTRY'].isin(valid_codes)]

In [450]:

export_base = sqlite3.connect('sdmdb.db')
cur = export_base.cursor()

cur.execute("PRAGMA foreign_keys = OFF;")

# =========================
# 1. ROOT TABLES (NO FK)
# =========================
root = [
    ("age_group", age_group, ["AGE_GROUP_CODE","UPPER_AGE","LOWER_AGE"]),
    ("customer_segment", customer_segment, ["SEGMENT_CODE","LANGUAGE","SEGMENT_NAME","SEGMENT_DESCRIPTION"]),
    ("customer_type", customer_type, ["CUSTOMER_TYPE_CODE","CUSTOMER_TYPE_EN"]),
    ("sales_territory", sales_territory, ["SALES_TERRITORY_CODE","TERRITORY_NAME_EN"]),
    ("order_method", order_method, ["ORDER_METHOD_CODE","ORDER_METHOD_EN"]),
    ("product_line", product_line, ["PRODUCT_LINE_CODE","PRODUCT_LINE_EN"]),
    ("return_reason", return_reason, ["RETURN_REASON_CODE","RETURN_DESCRIPTION"]),
    ("course", course, ["COURSE_CODE","COURSE_DESCRIPTION"]),
    ("satisfaction_type", satisfaction_type, ["SATISFACTION_TYPE_CODE","SATISFACTION_TYPE_DESCRIPTION"]),
]

# =========================
# 2. SECOND LAYER
# =========================
mid = [
    ("go_sales_country", country, ["COUNTRY_CODE","COUNTRY","LANGUAGE","CURRENCY_NAME"]),

    ("crm_country", crm_country, [
        "COUNTRY_CODE","COUNTRY_EN","FLAG_IMAGE","SALES_TERRITORY"
    ]),

    ("product_type", product_type, [
        "PRODUCT_TYPE_CODE","PRODUCT_TYPE_EN","PRODUCT_LINE"
    ]),

    ("sales_branch", sales_branch, [
        "SALES_BRANCH_CODE","ADRESS1","ADRESS2","CITY","REGION","POSTAL_CODE","COUNTRY"
    ]),

    ("sales_office", sales_office, [
        "SALES_OFFICE_CODE","STREET","ADDITION","CITY","REGION","ZIPCODE","COUNTRY"
    ]),
]

# =========================
# 3. THIRD LAYER
# =========================
third = [
    ("customer_headquarters", customer_headquarters, [
        "CUSTOMER_CODE_HQ","CUSTOMER_NAME","ADRESS1","ADRESS2",
        "CITY","REGION","POSTAL_ZONE","PHONE","FAX","COUNTRY"
    ]),

    ("product", product, [
        "PRODUCT_NUMBER","DESCRIPTION","INTRODUCTION_DATE",
        "PRODUCTION_COST","MARGIN","PRODUCT_IMG",
        "LANGUAGE","PRODUCT_NAME","PRODUCT_TYPE"
    ]),

    ("sales_staff", sales_staff, [
        "SALES_STAFF_CODE","FIRST_NAME","LAST_NAME","POSITION_EN",
        "WORK_PHONE","EXTENSION","FAX","DATE_HIRED","SALES_BRANCH"
    ]),

    ("sales_representative", sales_representative, [
        "SALES_REPRESENTATIVE_CODE","FIRST_NAME","LAST_NAME","POSITION_EN",
        "WORK_PHONE","EXTENSION","FAX","EMAIL","DATE_HIRED",
        "SALES_OFFICE","MANAGER"
    ]),

    ("customer", customer, [
        "CUSTOMER_CODE","COMPANY_NAME","CUSTOMER_TYPE","CUSTOMER_HEADQUARTERS"
    ]),
]

# =========================
# 4. FACT TABLES
# =========================
fact = [
    ("customer_store", customer_store, [
        "CUSTOMER_STORE_CODE","STREET","ADDITION","CITY","STATE",
        "ZIPCODE","ACTIVE_INDICATOR","CUSTOMER","CRM_COUNTRY"
    ]),

    ("customer_contact", customer_contact, [
        "CUSTOMER_CONTACT_CODE","FIRST_NAME","LAST_NAME",
        "JOB_POSITION_EN","EXTENSION","FAX","E_MAIL",
        "GENDER","CUSTOMER_STORE"
    ]),

    ("sales_demographic", sales_demographic, [
        "DEMOGRAPHIC_CODE","SALES_PERCENT",
        "CUSTOMER_HEADQUARTERS","AGE_GROUP"
    ]),

    ("order_header", order_header, [
        "ORDER_NUMBER","RETAILER_NAME","RETAILER_CONTACT_CODE",
        "ORDER_DATE","RETAILER_SITE","SALES_STAFF",
        "SALES_BRANCH","ORDER_METHOD"
    ]),

    ("order_details", order_details, [
        "ORDER_DETAIL_CODE","QUANTITY","UNIT_COST","UNIT_PRICE",
        "UNIT_SALE_PRICE","ORDER_HEADER","PRODUCT"
    ]),

    ("returned_item", returned_item, [
        "RETURN_CODE","RETURN_DATE","RETURN_QUANTITY",
        "ORDER_DETAILS","RETURN_REASON"
    ]),

    ("inventory_level", inventory_levels, [
        "INVENTORY_LEVELS_CODE","INVENTORY_YEAR",
        "INVENTORY_MONTH","INVENTORY_COUNT","PRODUCT"
    ]),

    ("product_forecast", product_forecast, [
        "PRODUCT_FORECAST_CODE","YEAR","MONTH",
        "EXPECTED_VOLUME","PRODUCT"
    ]),

    ("sales_target", sales_target, [
        "SALES_TARGET_CODE","SALES_YEAR","SALES_PERIOD",
        "RETAILER_NAME","RETAILER_CODE","SALES_TARGET",
        "SALES_STAFF","PRODUCT"
    ]),

    ("satisfaction", satisfaction, [
        'YEAR', 'SALES_REPRESENTATIVE_CODE', 'SATISFACTION_TYPE_CODE',
       'SATISFACTION_CODE'
    ]),

    ("training", training, [
        "YEAR","SALES_REPRESENTATIVE_CODE","COURSE_CODE"
    ]),
]

# =========================
# ORDERED EXECUTION
# =========================
all_tables = root + mid + third + fact

for table_name, df, cols in all_tables:

    missing = set(cols) - set(df.columns)
    if missing:
        print(f"❌ {table_name} mist: {missing}")
        continue

    df_clean = df[cols]

    query = f"""
    INSERT OR REPLACE INTO {table_name}
    ({",".join(cols)})
    VALUES ({",".join(["?"] * len(cols))})
    """

    try:
        cur.executemany(query, df_clean.values.tolist())
        print(f"✔ {table_name}")
    except Exception as e:
        print(f"❌ {table_name} ERROR: {e}")
        break

export_base.commit()
export_base.close()

✔ age_group
✔ customer_segment
✔ customer_type
✔ sales_territory
✔ order_method
✔ product_line
✔ return_reason
✔ course
✔ satisfaction_type
✔ go_sales_country
✔ crm_country
✔ product_type
✔ sales_branch
✔ sales_office
✔ customer_headquarters
✔ product
✔ sales_staff
✔ sales_representative
✔ customer
✔ customer_store
✔ customer_contact
✔ sales_demographic
✔ order_header
✔ order_details
✔ returned_item
✔ inventory_level
✔ product_forecast
✔ sales_target
❌ satisfaction ERROR: table satisfaction has no column named SALES_REPRESENTATIVE_CODE